services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    networks:
      - apps_net
      - tunnel_net

  whoami: 
    image: traefik/whoami
    networks:
      - apps_net

networks:
  apps_net:
    name: apps_net
    external: true
  
  tunnel_net:
    name: tunnel_net
    external: true

volumes:
  caddy_data:
  caddy_config: